%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\Eren\Dropbox\DERSLER\2016-2017
%    Fall\EE574\Project\ieee_cdf.dat
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2016/12/08 23:39:40

%% Initialize variables.
filename = 'C:\Users\Eren\Dropbox\DERSLER\2016-2017 Fall\EE574\Project\ieee_cdf.dat';
delimiter = ' ';
startRow = 3;
endRow = 5;

%% Format string for each line of text:
%   column1: double (%f)
%	column2: text (%s)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%s%f%f%f%f%f%f%f%f%f%f%*s%*s%*s%*s%*s%*s%*s%*s%*s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow-startRow+1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'HeaderLines', startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
VarName1 = dataArray{:, 1};
UW = dataArray{:, 2};
ARCHIVE = dataArray{:, 3};
VarName4 = dataArray{:, 4};
VarName5 = dataArray{:, 5};
W = dataArray{:, 6};
IEEE = dataArray{:, 7};
VarName8 = dataArray{:, 8};
Bus = dataArray{:, 9};
Test = dataArray{:, 10};
Case = dataArray{:, 11};
VarName12 = dataArray{:, 12};

%% Clear temporary variables
clearvars filename delimiter startRow endRow formatSpec fileID dataArray ans;